entry/urls.py
from django.urls import path
from .views import EntryListCreateView

urlpatterns = [
    path('', EntryListCreateView.as_view(), name='entry-list-create')
]

socialnews/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from socialnews.sitemaps import StorySitemap

from .feeds import LatesStoryFeed
from .views import (EditStory, NewStory, PanelView, ProfileView,
                    RegisterUserView, ShowStory, StoryListView, downvote_stroy,
                    fetch_title, story_search, upvote_story,
                    ProfileEditView, email_confirmation,
                    Test)
from .apiviews import StoryListCreateApiView, LoginApiView, StoryDetailApiView

sitemaps = {
    'stories': StorySitemap
}

app_name = 'socialnews'
urlpatterns = [
    ###################
    # AUTH            #
    ###################

    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='socialnews/login.html'),
         name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'),
         name='logout'),

    path('accounts/register/', RegisterUserView.as_view(),
         name='register_user'),
    path('accounts/password_change', auth_views.PasswordChangeView.as_view(
        success_url='/accounts/password_change_done'),
        name='password_change'),
    path('accounts/password_change_done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(
             success_url='/accounts/password_reset_done'),
         name='password_reset'),
    path('accounts/password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             success_url='/accounts/reset/done'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('accounts/email_confirmation/<token>/<code>',
         email_confirmation, name='email_confitmation'),

    ###################
    # PROFILE         #
    ###################

    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/profile/edit/', ProfileEditView.as_view(),
         name='profile_edit'),

    ###################
    # STORIES         #
    ###################

    path('', StoryListView.as_view(), name='index'),
    path('story/tag/<slug:tag_slug>',
         StoryListView.as_view(), name='story_list_by_tag'),
    path('story/latest/', StoryListView.as_view(), name='latest_stories'),
    path('story/<int:id>', ShowStory.as_view(), name='show_story'),
    path('story/upvote/<int:id>', upvote_story, name='upvote_story'),
    path('story/downvote/<int:id>', downvote_stroy, name='downvote_story'),
    path('story/new', NewStory.as_view(), name='new_story'),
    path('story/edit/<int:id>', EditStory.as_view(), name='edit_story'),
    path('story/site', StoryListView.as_view(), name='stories_by_domain'),
    path('story/fetch_title', fetch_title, name='fetch_title'),

    ###################
    # OTHER           #
    ###################

    path('panel/', PanelView.as_view(), name='admin'),
    path('test/', Test.as_view()),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.view.sitemap'),
    path('feed/', LatesStoryFeed(), name='story_feed'),
    path('search/', story_search, name='story_search'),

    ###################
    # API             #
    ###################
    path('api/stories/', StoryListCreateApiView.as_view()),
    path('api/story/<pk>/', StoryDetailApiView.as_view(), name='story-detail'),
    path('api/login/', LoginApiView.as_view()),
    # path('api/users/<pk>')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

socialnews/models.py
import uuid
from datetime import datetime, timedelta

import jwt
from django.conf import settings
# from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
#                                         PermissionsMixin)
from django.contrib.auth.models import User
# from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.db import models
from django.template import loader
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_jalali.db import models as jmodels
from taggit.managers import TaggableManager

from .utils import get_domain


class TimeStampedModel(models.Model):
    objects = jmodels.jManager()
    created = jmodels.jDateTimeField(auto_now_add=True)
    modified = jmodels.jDateTimeField(auto_now=True)

    class Meta:
        abstract = True


class SocialUser(User):
    class Meta:
        proxy = True

    @property
    def token(self):
        return self._generate_jwt_token()

    def _generate_jwt_token(self):
        """
        Generates a JSON Web Token that stores this user's ID and has an expiry
        date set to 60 days into the future.
        """
        dt = datetime.now() + timedelta(days=60)
        token = jwt.encode({
            'id': self.pk,
            'expire': int(dt.strftime('%s'))
        }, settings.SECRET_KEY, algorithm='HS256')

        return token.decode('utf-8')


class StoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class Story(TimeStampedModel):
    objects = models.Manager()
    stories = StoryManager()

    title = models.CharField(_('title'), max_length=500)
    story_url = models.URLField(
        _('url'), max_length=2000, blank=True, null=True)
    story_body_text = models.TextField(
        _('sotry body text (use markdown)'), blank=True, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='stories'
    )
    deleted = models.BooleanField(default=False)
    number_of_comments = models.IntegerField(default=0)
    number_of_votes = models.IntegerField(default=0)
    url_domain_name = models.CharField(max_length=500, blank=True)
    tags = TaggableManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']

    def update_number_of_comments(self):
        self.number_of_comments = self.comments.count()
        self.save()

    def update_number_of_votes(self):
        self.number_of_votes = self.storypoint_set.count()
        self.save()

    def save(self, *args, **kwargs):
        if self.story_url:
            self.url_domain_name = get_domain(self.story_url)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("socialnews:show_story", args=[self.id])


class StoryComment(TimeStampedModel):
    commenter = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    story = models.ForeignKey(
        Story, on_delete=models.CASCADE, related_name='comments')
    story_comment = models.TextField()
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.story_comment[:100]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Call the real save() method
        self.story.update_number_of_comments()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        self.story.update_number_of_comments()


class StoryPoint(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    story = models.ForeignKey(Story, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.story.update_number_of_votes()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        self.story.update_number_of_votes()


class Profile(models.Model):
    objects = jmodels.jManager()
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = jmodels.jDateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    activation_code = models.UUIDField(default=uuid.uuid4)
    token = models.UUIDField(default=uuid.uuid4)

    def send_activation_code(self, request, use_https=False):
        """
        Send activation code to user's email
        """
        current_site = get_current_site(request)
        message = loader.render_to_string(
            'socialnews/profile/activation_email.html', {
                'code': self.activation_code,
                'domain': current_site.domain,
                'protocol': 'https' if use_https else 'http',
                'token': self.token
            })
        send_mail(
            'Activating your account',
            message,
            'info@byteland.ir',
            [self.user.email],
            fail_silently=False,
        )

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

socialnews/forms.py
from django import forms
from django.contrib.auth.models import User
from django_jalali import forms as jforms
from django.utils.translation import gettext_lazy as _

from .models import Profile, Story, StoryComment


class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['story_url', 'title', 'story_body_text', 'tags']
        widgets = {
            'story_url': forms.URLInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'story_body_text': forms.Textarea(attrs={'class': 'form-control'})
        }


class StoryCommentForm(forms.ModelForm):
    class Meta:
        model = StoryComment
        fields = ['story_comment']
        widgets = {
            'story_comment': forms.Textarea(attrs={'class': 'form-control'})
        }


class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(label=_('Password'),
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control'}))
    password2 = forms.CharField(label=_('Reapet password'),
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            if email and User.objects.get(email=email):
                raise forms.ValidationError('Email address must be unique')
        except User.DoesNotExist:
            return email


class SearchForm(forms.Form):
    q = forms.CharField()


class EditUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True,
                               label='Username',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control'}))

    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        email_exist = User.objects.filter(email=email)
        email_exist.exclude(username=username).exists()
        if email and email_exist:
            raise forms.ValidationError('Email address must be unique')
        else:
            return email


class EditProfileForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields = ('photo', 'date_of_birth',)
        widgets = {
            'date_of_birth': jforms.widgets.jDateInput(
                attrs={'class': 'form-control datepicker'}
            )
        }

socialnews/templates/socialnews/base.html
{% load render_bundle from webpack_loader %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% if LANGUAGE_BIDI %}
    <html lang="fa" class="rtl">
{% else %}
    <html lang="{{ LANGUAGE_CODE }}">
{% endif %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Meysam Shirdel">

    <title>{% block title%}{% endblock %}</title>
    {% render_bundle 'main' 'css' %}
    
</head>

<body>
    {% include "socialnews/navigation.html" %}
    {% include "socialnews/messages.html"%}
    <main id="main-content" role="main" class="margin-top-15 container {% if LANGUAGE_BIDI %} rtl {% endif %}">
        {% block content %} {% endblock %}
    </main>
    <br>
    {% include "socialnews/footer.html" %}
    
    {% render_bundle 'main' 'js' %}
    
    {% block javascript %}
    {% endblock %}

</body>

</html>

socialnews/templates/socialnews/edit_story.html
{% extends 'socialnews/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-10">
            <form action="{% url 'edit_story' id %}" method="POST">
                {% include 'socialnews/item_form.html' with form=form %}
                <button type="submit" class="btn btn-primary mt-2">ویرایش</button>
            </form>
        </div>
    </div>
{% endblock %}

socialnews/templates/socialnews/footer.html
<div id="footer">
    <div class="container">
        <p class="footer-block"><a href="{% url 'socialnews:story_feed' %}">Site Feeds</a></p>
    </div>
</div>

socialnews/templates/socialnews/index.html
{% extends 'socialnews/base.html'%}
{% load static %}
{% load i18n %}
{% load jformat %}
{% load socialnews_tags %}
{% block title%} {% trans "Heatblast - Social News" %} {% endblock %}
{% block content %}
    {% include 'socialnews/story/list.html' %}

    {% comment %}
    <p>Latest Posts: </p>
    {% show_latest_stories 5 %}
    {% endcomment %}

{% endblock %}
<!-- - {{ story.created|jformat:"%A %d %B %Y %H:%M"}}-->

socialnews/templates/socialnews/item_form.html
{% csrf_token %}
{% for field in form %}
    <div class="form-group">
        {{ field.errors}}
        {% if field.name == 'title' %}
            {{ field.label_tag }} 
            <button type="button" id="btnFetchTitle" class="btn btn-outline-info btn-sm font-size-12">واکشی عنوان</button> 
            {{ field }}
        {% else %}
        {{ field.label_tag }} {{ field }}
        {% endif %}
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor%}

socialnews/templates/socialnews/login.html
{% extends "socialnews/base.html" %}
{% load i18n %}
{% block title %} {% trans "Log in to HeatBlast - Social News" %} {% endblock %}
{% block content %}
{% include 'socialnews/render_form_errors.html' %}
{% if next %}
    <div class="row margin-top-20">
        <div class="col-md-12">
            {% if user.is_authenticated %}
                <p class="alert alert-danger" role="alert">
                    {% trans "Your account doesn't have access to this page. To proceed, please login with
                an account that has access." %}</p>
            {% else %}
                <p class="alert alert-danger" role="alert">{% trans "Please login to see this page." %}</p>
            {% endif %}
        </div>
    </div>
{% endif %}
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center custom-color">{% trans "Sign In" %}</h5>
                    <form method="POST" action="{% url 'socialnews:login' %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">
                        
                        <div class="form-group">
                            
                            <input type="text" name="username" autofocus required 
                                placeholder='{% trans "Email or Username" %}'
                                id="id_username" class="form-control">
                        </div>

                        <div class="form-group">
                            
                            <input type="password" name="password" id="id_password" class="form-control"
                                placeholder='{% trans "Password" %}'
                                required>
                        </div>

                        <div class="custom-control custom-checkbox mb-3">
                            <input type="checkbox" class="custom-control-input" id="customCheck1">
                            <label class="custom-control-label" for="customCheck1">{% trans "Remember password" %}</label>
                        </div>
                        <div class="form-group text-center">
                            <button class="btn btn-success" type="submit">{% trans "Sign in" %}</button>
                        </div>
                        <div class="form-group">
                            <a href="{% url 'socialnews:password_reset' %}">
                                {% trans "Forgotten your password?" %}
                            </a>
                        </div>
                        <div class="form-group">
                            <a href="{% url 'socialnews:register_user' %}" >
                                {% trans "Register" %}
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

socialnews/templates/socialnews/messages.html
{% if messages %}
<div class='container margin-top-20'>
    <div class="row">
        <div class="col-md-12">
            <div class='message-alert'>
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
</div>
{% endif %}

socialnews/templates/socialnews/navigation.html
{% load i18n %}
<!-- Navigation -->
<div class="container">
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'socialnews:index' %}">
        {% trans 'byteland.ir' %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'socialnews:latest_stories' %}">
                    {% trans 'Newest Stories' %}
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'socialnews:new_story' %}">{% trans 'New Link' %}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'socialnews:login' %}">{% trans 'Login' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'socialnews:register_user' %}">{% trans 'Register' %}</a>
            </li>
            {% endif %}

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'socialnews:profile'%}">{% trans 'Profile' %}</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'socialnews:logout' %}">{% trans 'Log out' %}</a>
            </li>
            {% endif %}
        </ul>
        {% include 'socialnews/search.html'%}
    </div>
</nav>
</div>

socialnews/templates/socialnews/pagination.html
{% load socialnews_filters %}
<ul class="pagination">
    {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </li>
    {% endif %}
 
    {% for i in page.paginator.num_pages|times %}
    {% if page.number == forloop.counter %}
    <li class="page-item active">
        <span class="page-link"> {{ forloop.counter }} </span>
    </li>
    {% else %}
    <li class="page-item">
        <a href="?page={{ forloop.counter }}" class="page-link"> {{ forloop.counter }} </a>
    </li>
    {% endif %}
    {% endfor %}

    {% if page.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">Next</a>
    </li>
    {% endif %}

</ul>

socialnews/templates/socialnews/panel.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'socialnews/styles/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'socialnews/styles/bootstrap-rtl.css' %}" rel="stylesheet">
    <link href="{% static 'socialnews/styles/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'socialnews/styles/general.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'socialnews/styles/panel.css' %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sign out</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Dashboard</h1>
            </div>

            <!--<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>-->

        </main>
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">
                            <span data-feather="home"></span>
                            پنل مدیر <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file"></span>
                            Orders
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="shopping-cart"></span>
                            Products
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="users"></span>
                            Customers
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="bar-chart-2"></span>
                            Reports
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Saved reports</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Current month
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Last quarter
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Social engagement
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Year-end sale
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'socialnews/javascripts/jquery/jquery.min.js' %}"></script>
<script src="{% static 'socialnews/javascripts/bootstrap/bootstrap.bundle.min.js' %}"></script>
<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
      feather.replace()
</script>
</body>
</html>

socialnews/templates/socialnews/render_form.html
{% csrf_token %}
{% for field in form %}
    <div class="form-group">
        {{ field.errors}}
        {{ field.label_tag }} 
        {{ field }}
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor%}

socialnews/templates/socialnews/search.html
{% load i18n %}
<div class="row">
    <div class="col-md-12">
        <form action="{% url 'socialnews:story_search' %}" method="GET" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="q" required="" id="id_q">
            <input type="submit" value="{% trans 'search' %}" class="btn btn-outline-primary my-2 my-sm-0">
        </form>
    </div>
</div>

socialnews/templates/socialnews/search_result.html
{% extends 'socialnews/base.html' %}
{% block title%} Search Result {% endblock %}
{% block content %}
    {% if query %}
        <h1>Stories containing "{{ query }}" </h1>
        <h3>Found {{ results.count }}</h3>
        {% for story in results %}
            <a href="{{ story.get_absolute_url }}">{{ story.title }}</a>
            <hr>
        {% empty %}
            <p>Nothing :)</p>
        {% endfor %}
    {% else %}
        <h3>Search</h3>
        {% include 'socialnews/search.html'%}
    {% endif %}
{% endblock %}

socialnews/templates/socialnews/show_story.html
{% extends 'socialnews/base.html'%}
{% load jformat %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if story.url %}
                <a href="{{story.url}}" target="_blank"><h1>{{story.title}}</h1></a>
            {% else %}
                <h1>{{story.title}}</h1>
            {% endif %}
        </div>
    </div>
    <div class="row font-size-10">
        <div class="col-md-12">
            ایجاد شده توسط:
            {{ story.user.username }}
            در {{ story.created|jformat:"%H:%M %Y/%m/%d"}}
        </div>
    </div>
    <div class="row padding-top-10">
        <div class="col-md-12">
            <p>{{story.story_body_text}}</p>
        </div>
    </div>
    <div class="row padding-top-10">
        <div class="col-md-12">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-primary mt-2">ارسال</button>
            </form>
        </div>
    </div>
    <div class="row padding-top-10">
            <div class="col-md-12">
                {% for comment in story.storycomment_set.all %}
                    <i><b>{{ comment.created|jformat:"%H:%M %Y/%m/%d" }} - {{ comment.commenter.username }}</b></i>
                    <p>{{ comment.story_comment }}</p>
                {% endfor %}
            </div>
        </div>
{% endblock %}