entry/urls.py
from django.urls import path
from .views import EntryListCreateView

urlpatterns = [
    path('', EntryListCreateView.as_view(), name='entry-list-create')
]

socialnews/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from socialnews.sitemaps import StorySitemap

from .feeds import LatesStoryFeed
from .views import (EditStory, NewStory, PanelView, ProfileView,
                    RegisterUserView, ShowStory, StoryListView, downvote_stroy,
                    fetch_title, story_search, upvote_story,
                    ProfileEditView, email_confirmation,
                    Test)
from .apiviews import StoryListCreateApiView, LoginApiView, StoryDetailApiView

sitemaps = {
    'stories': StorySitemap
}

app_name = 'socialnews'
urlpatterns = [
    ###################
    # AUTH            #
    ###################

    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='socialnews/login.html'),
         name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'),
         name='logout'),

    path('accounts/register/', RegisterUserView.as_view(),
         name='register_user'),
    path('accounts/password_change', auth_views.PasswordChangeView.as_view(
        success_url='/accounts/password_change_done'),
        name='password_change'),
    path('accounts/password_change_done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(
             success_url='/accounts/password_reset_done'),
         name='password_reset'),
    path('accounts/password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             success_url='/accounts/reset/done'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('accounts/email_confirmation/<token>/<code>',
         email_confirmation, name='email_confitmation'),

    ###################
    # PROFILE         #
    ###################

    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/profile/edit/', ProfileEditView.as_view(),
         name='profile_edit'),

    ###################
    # STORIES         #
    ###################

    path('', StoryListView.as_view(), name='index'),
    path('story/tag/<slug:tag_slug>',
         StoryListView.as_view(), name='story_list_by_tag'),
    path('story/latest/', StoryListView.as_view(), name='latest_stories'),
    path('story/<int:id>', ShowStory.as_view(), name='show_story'),
    path('story/upvote/<int:id>', upvote_story, name='upvote_story'),
    path('story/downvote/<int:id>', downvote_stroy, name='downvote_story'),
    path('story/new', NewStory.as_view(), name='new_story'),
    path('story/edit/<int:id>', EditStory.as_view(), name='edit_story'),
    path('story/site', StoryListView.as_view(), name='stories_by_domain'),
    path('story/fetch_title', fetch_title, name='fetch_title'),

    ###################
    # OTHER           #
    ###################

    path('panel/', PanelView.as_view(), name='admin'),
    path('test/', Test.as_view()),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.view.sitemap'),
    path('feed/', LatesStoryFeed(), name='story_feed'),
    path('search/', story_search, name='story_search'),

    ###################
    # API             #
    ###################
    path('api/stories/', StoryListCreateApiView.as_view()),
    path('api/story/<pk>/', StoryDetailApiView.as_view(), name='story-detail'),
    path('api/login/', LoginApiView.as_view()),
    # path('api/users/<pk>')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

socialnews/forms.py
from django import forms
from django.contrib.auth.models import User
from django_jalali import forms as jforms
from django.utils.translation import gettext_lazy as _

from .models import Profile, Story, StoryComment


class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['story_url', 'title', 'story_body_text', 'tags']
        widgets = {
            'story_url': forms.URLInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'story_body_text': forms.Textarea(attrs={'class': 'form-control'})
        }


class StoryCommentForm(forms.ModelForm):
    class Meta:
        model = StoryComment
        fields = ['story_comment']
        widgets = {
            'story_comment': forms.Textarea(attrs={'class': 'form-control'})
        }


class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(label=_('Password'),
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control'}))
    password2 = forms.CharField(label=_('Reapet password'),
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            if email and User.objects.get(email=email):
                raise forms.ValidationError('Email address must be unique')
        except User.DoesNotExist:
            return email


class SearchForm(forms.Form):
    q = forms.CharField()


class EditUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True,
                               label='Username',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control'}))

    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        email_exist = User.objects.filter(email=email)
        email_exist.exclude(username=username).exists()
        if email and email_exist:
            raise forms.ValidationError('Email address must be unique')
        else:
            return email


class EditProfileForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields = ('photo', 'date_of_birth',)
        widgets = {
            'date_of_birth': jforms.widgets.jDateInput(
                attrs={'class': 'form-control datepicker'}
            )
        }

socialnews/views.py
import requests
import uuid
from bs4 import BeautifulSoup
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Permission, User
from django.contrib.postgres.search import (SearchQuery, SearchRank,
                                            SearchVector)
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic import ListView
from taggit.models import Tag

from .forms import (EditProfileForm, EditUserForm, RegisterUserForm,
                    SearchForm, StoryCommentForm, StoryForm)
from .models import Profile, Story, StoryComment, StoryPoint


class StoryListView(ListView):
    queryset = Story.stories.all().order_by('-number_of_votes')
    context_object_name = 'stories'
    paginate_by = settings.PAGE_SIZE
    template_name = 'socialnews/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        voted_story_id = []
        if self.request.user.is_authenticated:
            for point in self.request.user.storypoint_set.all():
                voted_story_id.append(point.story_id)
        context['voted_story_id'] = voted_story_id
        return context

    def get_queryset(self):
        query_set = super().get_queryset()
        if self.request.GET.get('url'):
            url = self.request.GET.get('url')
            return query_set.filter(url_domain_name=url)
        if self.kwargs.get('tag_slug'):
            tag_slug = self.kwargs.get('tag_slug')
            tag = get_object_or_404(Tag, slug=tag_slug)
            messages.add_message(self.request,
                                 messages.INFO,
                                 f"Stories tagged with {tag_slug}")
            return query_set.filter(tags__in=[tag])
        if self.request.path == '/story/latest/':
            return Story.stories.all().order_by('-created')
        return query_set


class ShowStory(View):
    def get(self, request, id):
        story = get_object_or_404(Story, pk=id)
        story_tags_ids = story.tags.values_list('id', flat=True)
        similar_stories = Story.stories.filter(
            tags__in=story_tags_ids).exclude(id=story.id)
        similar_stories = similar_stories.annotate(
            same_tags=Count('tags')).order_by('-same_tags', '-created')[:4]
        story_comment_form = StoryCommentForm()
        return render(request, 'socialnews/story/show.html',
                      {
                          'story': story,
                          'form': story_comment_form,
                          'similar_stories': similar_stories
                      })

    def post(self, request, id):
        story = get_object_or_404(Story, pk=id)
        if request.user.is_authenticated:
            form = StoryCommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.commenter = request.user
                comment.story = story
                comment.save()
                return render(request, 'socialnews/story/show.html',
                              {'story': story, 'form': StoryCommentForm})
            else:
                return render(request, 'socialnews/story/show.html',
                              {'story': story, 'form': form})
        else:
            form = StoryCommentForm()
            messages.add_message(request,
                                 messages.WARNING,
                                 _('Please Register to site for commenting')
                                 )
            return render(request, 'socialnews/story/show.html',
                          {'story': story, 'form': form})


@method_decorator(login_required, name='dispatch')
class NewStory(PermissionRequiredMixin, View):
    # 'socialnews.add_story'
    permission_required = []

    def get(self, request):
        form = StoryForm()
        return render(request, 'socialnews/story/new.html', {'form': form})

    def post(self, request):
        form = StoryForm(request.POST)
        if form.is_valid():
            story = form.save(commit=False)
            story.user = request.user
            story.save()
            form.save_m2m()
            return HttpResponseRedirect('/')
        else:
            return render(request, 'socialnews/story/new.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class EditStory(View):
    def get(self, request, id):
        story = get_object_or_404(Story, pk=id)
        form = StoryForm(instance=story)
        return render(request, 'socialnews/story/edit.html',
                      {'form': form, 'id': id})

    def post(self, request, id):
        story = get_object_or_404(Story, pk=id)
        form = StoryForm(request.POST, instance=story)
        if form.is_valid():
            story.tags.clear()
            for tag_slug in form.cleaned_data['tags']:
                story.tags.add(tag_slug)
            story.save()
            # form.save_m2m()
            # produce error => 'StoryForm' object has no attribute 'save_m2m'
            return HttpResponseRedirect('/')
        else:
            return render(request, 'socialnews/story/edit.html',
                          {'form': form, 'id': id})


@login_required()
def upvote_story(request, id):
    result_url = '/'
    if request.GET.get('page'):
        result_url = f"/?page={request.GET.get('page')}"
    story = get_object_or_404(Story, pk=id)
    try:
        StoryPoint.objects.get(user=request.user, story=story)
        return HttpResponseRedirect(result_url)
    except StoryPoint.DoesNotExist:
        story_point = StoryPoint(user=request.user, story=story)
        story_point.save()
        return HttpResponseRedirect(result_url)


@login_required()
def downvote_stroy(request, id):
    result_url = '/'
    if request.GET.get('page'):
        result_url = f"/?page={request.GET.get('page')}"
    try:
        story_point = StoryPoint.objects.get(user=request.user, story_id=id)
        story_point.delete()
    except StoryPoint.DoesNotExist:
        pass
    return HttpResponseRedirect(result_url)


class PanelView(View):
    def get(self, request):
        return render(request, 'socialnews/panel.html')


@method_decorator(login_required, name='dispatch')
class ProfileView(View):
    def get(self, request):
        user_stories = Story.stories.filter(user=request.user)
        paginator = Paginator(user_stories, settings.PAGE_SIZE)
        page = request.GET.get('page')
        try:
            stories = paginator.get_page(page)
        except PageNotAnInteger:
            stories = paginator.get_page(1)
        except EmptyPage:
            stories = paginator(paginator.num_pages)

        return render(request,
                      'socialnews/profile/profile.html',
                      {"stories": stories})


@method_decorator(login_required, name='dispatch')
class ProfileEditView(View):
    def get(self, request):
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.profile)
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, 'socialnews/profile/edit.html', context)

    def post(self, request):
        user_form = EditUserForm(instance=request.user, data=request.POST)
        profile_form = EditProfileForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your profile was updated")
        else:
            messages.error(request, "Somthing goes wrong")
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }

        return render(request, 'socialnews/profile/edit.html', context)


class RegisterUserView(View):
    def get(self, request):
        form = RegisterUserForm()
        return render(request, 'socialnews/register_user.html', {'form': form})

    def post(self, request):
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.is_active = False
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            profile.send_activation_code(request)
            messages.success(request,
                             _('Successfully created your account. \
                                for activating it check your email'))
            return HttpResponseRedirect('/')
        else:
            return render(request,
                          'socialnews/register_user.html',
                          {'form': form})


def email_confirmation(request, token, code):
    user_token = uuid.UUID(token)
    user = get_object_or_404(User, profile__token=user_token)
    if user.is_active:
        messages.info(request, _('Your account already activated'))
        return HttpResponseRedirect('/')
    if str(user.profile.activation_code) == code:
        user.is_active = True
        user.save()
        messages.success(request, _(
            "Your account is active. You can login now."))
        return HttpResponseRedirect('/')

socialnews/templates/socialnews/story/edit.html
{% extends 'socialnews/base.html' %}
{% load i18n %}
{% block content %}
    <div class="row margin-top-15">
        <div class="col-md-12">
            <form action="{% url 'socialnews:edit_story' id %}" method="POST">
                {% include 'socialnews/item_form.html' with form=form %}
                <button type="submit" class="btn btn-primary mt-2">{% trans "Edit" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

socialnews/templates/socialnews/story/list.html
{% load i18n %}
{% for story in stories %}
    <div class="row margin-top-20">
        <div class="col-md-12">
            {% if story.story_url %}
            <a href="{{story.story_url}}" class="story-link" target="_blank">{{story.title}}</a>
            {% else %}
            <a href="{{ story.get_absolute_url }}" class="story-link">{{story.title}}</a>
            {% endif %}
            {% if campact %}
                <a href="{% url 'socialnews:edit_story' story.id %}">{% trans "Edit" %}</a> |
                <a href="{{ story.get_absolute_url }}">{% trans "Comments" %}
                    {{ story.number_of_comments }}
                </a>
            {% endif %}
        </div>
    </div>
    {% if not campact %}
        <div class="row font-size-12 color-dimgray">
            <div class="col-md-12">
                {{ story.number_of_votes }} {% trans "points" %}
                {% trans "by" %} : {{ story.user.username }}
                {% trans "in" %} {{ story.created.togregorian|timesince }} {% trans "before" %}
                {% if user.is_authenticated and story.user == user %}
                    | <a href="{% url 'socialnews:edit_story' story.id %}">{% trans "Edit" %}</a>
                {% endif %} |
                <a href="{{ story.get_absolute_url }}">{% trans "Comments" %}
                    {{ story.number_of_comments }}
                </a> |
                {% if user.is_authenticated %}
                    {% if story.id in voted_story_id %}
                        <a id="downvote" href="{% url 'socialnews:downvote_story' story.id %}">
                            {% trans "Down Vote" %}
                        </a>
                    {% else %}
                        <a href="{% url 'socialnews:upvote_story' story.id %}">
                            {% trans "Vote" %}
                        </a>
                    {% endif %} |
                {% endif %}
                {% if story.story_url %}
                    <a href="{% url 'socialnews:stories_by_domain' %}?url={{ story.url_domain_name }}">
                        {{ story.url_domain_name }}
                    </a>
                {% endif %}
            </div>
        </div>
        {% include 'socialnews/story/render_tags.html' %}
    {% endif %}
{% endfor %}

<div id="divFooter" class="row justify-content-md-center padding-top-10">
    <div class="col-md-12">
        {% if page_obj %}
            {% include 'socialnews/pagination.html' with page=page_obj %}
        {% else %}
            {% include 'socialnews/pagination.html' with page=stories %}
        {% endif %}
    </div>
</div>

socialnews/templates/socialnews/story/new.html
{% extends 'socialnews/base.html' %}
{% load i18n %}
{% block content %}
    <div class="row margin-top-15">
        <div class="col-md-12">
            <form action="{% url 'socialnews:new_story' %}" method="POST">
                {% include 'socialnews/item_form.html' with form=form %}
                <button type="submit" class="btn btn-primary mt-2">{% trans 'Publish' %}</button>
                <div class="row margin-top-50">
                    <div class="col-md-12">
                        {% trans 'Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.'%}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

socialnews/templates/socialnews/story/render_tags.html
<div class="row">
    <div class="col-md-12">
        {% for tag in story.tags.all %}
            <a href="{% url 'socialnews:story_list_by_tag' tag.slug %}" class="badge badge-default">
                {{ tag.name }}
            </a>
        {% endfor %}
    </div>
</div>

socialnews/templates/socialnews/story/show.html
{% extends 'socialnews/base.html'%}
{% load jformat %}
{% load i18n %}
{% load socialnews_filters %}
{% block content %}
<div class="margin-top-15">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    {% if story.url %}
                    <a href="{{story.url}}" target="_blank">
                        <h1>{{story.title}}</h1>
                    </a>
                    {% else %}
                    <h1>{{story.title}}</h1>
                    {% endif %}
                </div>
            </div>
            <div class="row font-size-12">
                <div class="col color-dimgray">
                    {% blocktrans with username=story.user.profile created=story.created.togregorian|timesince %}
                    Created by: &nbsp;
                    <b> {{ username }} </b>
                    &nbsp;
                    <span> {{ created }} </span>
                    {% endblocktrans %}
                </div>
            </div>
            {% include 'socialnews/story/render_tags.html' %}
            <div class="row padding-top-10">
                <div class="col-md-12">
                    <p>{{story.story_body_text|markdown}}</p>
                </div>
            </div>
            
            <div class="row padding-top-10">
                <div class="col-md-12">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-primary mt-2">{% trans "Send" %}</button>
                    </form>
                </div>
            </div>
            {% for comment in story.comments.all %}
            <div class="row padding-top-10 margin-right-10">
                <div class="col-md-1">
                    {% include 'socialnews/profile/render_profile_photo.html' with user=comment.commenter size='48x48' %}
                </div>
                <div class='col-md-11'>
                    <span class="font-size-12 padding-top-3 color-dimgray">
                        {{ comment.commenter.profile }}
                        {{ comment.created.togregorian|timesince }}
                        {% trans "before" %}</span>
                    <p>{{ comment.story_comment }}</p>
                </div>
                
            </div>
            {% endfor %}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            {% trans "similar stories:" %} <br>
            <ul>
                {% for story in similar_stories %}
                <li>
                    <a href="{{ story.get_absolute_url }}">{{story.title}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}